build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:trixie"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:trixie"
  i386: "ghcr.io/home-assistant/i386-base-debian:trixie"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ebusd"
  org.opencontainers.image.description: "This Add-on runs eBUSd, a daemon for handling communication with eBUS devices"
  org.opencontainers.image.source: "https://github.com/aavdberg/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
